# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clockworkd}
  s.version = "0.2.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Wiggins", "Artem Rufanov"]
  s.date = %q{2011-07-31}
  s.description = %q{A scheduler process to replace cron, using a more flexible Ruby syntax running as a single long-running process.  Inspired by rufus-scheduler and resque-scheduler.}
  s.email = %q{developers@majoron.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = Dir.glob('**/*') - Dir.glob('distrib/**/*') - Dir.glob('lib/api/**/*') - Dir.glob('doc/*.xpr')
  s.homepage = %q{http://www.majoron.com/project/rbundle/clockworkd}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{clockworkd}
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A scheduler process to replace cron.}
  s.test_files = Dir.glob('spec/**/*')
  s.add_runtime_dependency 'tzinfo', '>= 0.3.23'

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

